const data = [
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 3,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 5,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 2,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Pfljsfjlyc logy of Money",
    author: "Morgafk smfn Housel",
    rating: 1,
    quantity: 0,
  },
];

export default data;
