const data = [
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
  {
    id: Math.random(),
    url: "",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    rating: 4,
    quantity: 0,
  },
];

export default data;
